################################# Default configuration ###################
# provide your domain here
baseURL = "https://kb.magic-connect.com"
# theme
theme = "faq"
# site title
title = "Magic Connect! Knowledge Base"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "Find answers to your Magic Connect! questions here!"
author = "Magic Connect! Team"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io

############################## social links ##############################
[[params.social]]
icon = "icon-facebook" # themify icon pack : https://themify.me/themify-icons
name = "Facebook"
link = "https://www.facebook.com/magicongame/"

[[params.social]]
icon = "icon-twitter" # themify icon pack : https://themify.me/themify-icons
name = "Twitter"
link = "https://www.twitter.com/magicongame/"
  
[[params.social]]
icon = "icon-reddit" # themify icon pack : https://themify.me/themify-icons
name = "Reddit"
link = "https://reddit.com/r/magicongame"
  
[[params.social]]
icon = "icon-discord" # themify icon pack : https://themify.me/themify-icons
name = "Discord"
link = "https://discord.gg/magicconnect"
  
[[params.social]]
icon = "icon-telegram" # themify icon pack : https://themify.me/themify-icons
name = "Telegram"
link = "https://t.me/magiconofficial"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright &copy; 2022"

# banner
[Languages.en.params.banner]
title = "Support Center & Knowledge Base"
subtitle = "Find advice and answers from our support team fast or get in touch"
bg_image = "images/banner.png"
placeholder = "Have a question? Search for relevant answers here."

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "You can reach out directly via email and a member of the team will get in touch with you."

# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "mailto:support@magic-connect.com"


################## english navigation #################
[[Languages.en.menu.main]]
name = "FAQ"
url = "faq/"
weight = 2

# Dropdown menu
[[Languages.en.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation/"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing/"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Features"
  url = "features/"
  weight = 3


